name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why?
      description: What problem does this solve, or what use case does it enable?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Frontend (UI/UX)
        - Backend (API/Server)
        - Encryption (E2EE)
        - Voice/Video (LiveKit)
        - Deployment/Infra
        - Other
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Additional details
      description: Mockups, examples from other apps, implementation ideas, etc.
