/**
 * Passphrase generator using a curated wordlist and crypto.getRandomValues().
 * Generates memorable passphrases like "correct-horse-battery-staple".
 */

// 1024-word curated list (10 bits of entropy per word)
// 6 words → ~60 bits, 8 words → ~80 bits
const WORDS = [
  "abandon","able","about","above","absorb","abstract","absurd","abuse",
  "access","acid","across","act","action","actual","adapt","add",
  "addict","address","adjust","admit","adult","advance","advice","afford",
  "again","age","agent","agree","ahead","aim","air","alarm",
  "album","alert","alien","all","alley","allow","almost","alone",
  "alpha","already","also","alter","always","amazing","among","amount",
  "amuse","anchor","ancient","angel","anger","angle","animal","ankle",
  "announce","annual","another","answer","antenna","antique","anxiety","any",
  "apart","apology","appear","apple","approve","april","arch","arctic",
  "area","arena","armor","army","arrange","arrest","arrive","arrow",
  "art","artist","asthma","atom","attack","attend","attract","auction",
  "audit","august","aunt","auto","autumn","average","avocado","avoid",
  "awake","aware","axis","baby","bachelor","bacon","badge","bag",
  "balance","balcony","ball","bamboo","banana","banner","bar","barely",
  "barrel","base","basic","basket","battle","beach","bean","beauty",
  "become","beef","before","begin","behave","behind","believe","bench",
  "benefit","best","betray","better","between","beyond","bicycle","bird",
  "birth","bitter","blade","blame","blanket","blast","blaze","bleak",
  "bless","blind","blood","blossom","blue","blur","blush","board",
  "boat","body","bomb","bone","bonus","book","boost","border",
  "boring","borrow","boss","bottom","bounce","bowl","brave","bread",
  "breeze","brick","bridge","brief","bright","bring","brisk","broken",
  "bronze","brother","brown","brush","bubble","buddy","budget","buffalo",
  "build","bulb","bulk","bullet","bundle","burger","burst","bus",
  "butter","buyer","cabin","cable","cactus","cage","cake","call",
  "calm","camera","camp","canal","cancel","candy","canoe","canvas",
  "canyon","capable","capital","captain","carbon","card","cargo","carpet",
  "carry","case","cash","castle","casual","catalog","catch","category",
  "cattle","caught","cause","caution","cave","ceiling","celery","cement",
  "census","century","cereal","certain","chair","chalk","champion","change",
  "chaos","chapter","charge","chase","cheap","check","cheese","cherry",
  "chest","chicken","chief","child","chimney","choice","chunk","cinema",
  "circle","citizen","city","civil","claim","clap","clarify","claw",
  "clean","clerk","clever","cliff","climb","clinic","clip","clock",
  "close","cloth","cloud","clown","club","cluster","clutch","coach",
  "coast","coconut","code","coffee","coil","coin","collect","color",
  "column","combine","come","comfort","comic","common","company","concert",
  "conduct","confirm","connect","consider","control","convince","cook","cool",
  "copper","copy","coral","core","corn","correct","cost","cotton",
  "couch","country","couple","course","cousin","cover","craft","crane",
  "crash","crater","crawl","crazy","cream","credit","crew","cricket",
  "crime","crisp","cross","crouch","crowd","crucial","cruel","cruise",
  "crumble","crush","crystal","cube","culture","cup","cupboard","curious",
  "current","curtain","curve","cushion","custom","cute","cycle","dad",
  "damage","dance","danger","daring","dash","daughter","dawn","day",
  "deal","debate","debris","decade","december","decide","decline","decorate",
  "decrease","deer","defense","define","defy","degree","delay","deliver",
  "demand","denial","dentist","deny","depart","depend","deposit","depth",
  "deputy","derive","describe","desert","design","desk","despair","destroy",
  "detail","detect","develop","device","devote","diamond","diary","diesel",
  "differ","digital","dignity","dilemma","dinner","dinosaur","direct","dirt",
  "disagree","discover","disease","dish","dismiss","disorder","display","distance",
  "divert","divide","divorce","dizzy","doctor","document","dog","dolphin",
  "domain","donate","donkey","donor","door","dose","double","dove",
  "draft","dragon","drama","drastic","draw","dream","dress","drift",
  "drill","drink","drip","drive","drop","drum","dry","duck",
  "dumb","dune","during","dust","dutch","duty","dwarf","dynamic",
  "eager","eagle","early","earn","earth","east","easy","echo",
  "ecology","economy","edge","edit","educate","effort","eight","either",
  "elbow","elder","electric","elegant","element","elephant","elevator","elite",
  "else","embark","embody","embrace","emerge","emotion","employ","empower",
  "empty","enable","enact","end","endless","endorse","enemy","energy",
  "enforce","engage","engine","enhance","enjoy","enlist","enough","enrich",
  "enroll","ensure","enter","entire","entry","envelope","episode","equal",
  "equip","era","erase","erode","erosion","error","erupt","escape",
  "essay","essence","estate","eternal","ethics","evidence","evil","evolve",
  "exact","example","excess","exchange","excite","exclude","excuse","execute",
  "exercise","exhaust","exhibit","exist","exit","exotic","expand","expect",
  "expire","explain","expose","express","extend","extra","eye","fabric",
  "face","faculty","fade","faint","faith","fall","false","family",
  "famous","fan","fancy","fantasy","farm","fashion","fatal","father",
  "fatigue","fault","favorite","feature","february","federal","feel","female",
  "fence","festival","fetch","fever","few","fiber","fiction","field",
  "figure","file","film","filter","final","find","finger","finish",
  "fire","firm","fiscal","fish","fit","fitness","fix","flag",
  "flame","flash","flat","flavor","flee","flight","flip","float",
  "flock","floor","flower","fluid","flush","fly","foam","focus",
  "fog","foil","fold","follow","food","foot","force","forest",
  "forget","fork","fortune","forum","forward","fossil","foster","found",
  "fox","fragile","frame","frequent","fresh","friend","fringe","frog",
  "front","frost","frown","frozen","fruit","fuel","fun","funny",
  "furnace","fury","future","gadget","galaxy","gallery","game","gap",
  "garage","garbage","garden","garlic","garment","gas","gasp","gate",
  "gather","gauge","gaze","general","genius","genre","gentle","genuine",
  "gesture","ghost","giant","gift","giggle","ginger","giraffe","glad",
  "glance","glare","glass","glide","glimpse","globe","gloom","glory",
  "glove","glow","glue","goat","goddess","gold","good","goose",
  "gorilla","gospel","gossip","govern","gown","grab","grace","grain",
  "grant","grape","grass","gravity","great","green","grid","grief",
  "grit","grocery","group","grow","grunt","guard","guess","guide",
  "guilt","guitar","gun","gym","habit","half","hammer","hamster",
  "hand","happy","harbor","hard","harsh","harvest","hat","have",
  "hawk","hazard","head","health","heart","heavy","hedgehog","height",
  "hello","help","hen","hero","hidden","high","hill","hint",
  "hip","hire","history","hobby","hockey","hold","hole","holiday",
  "hollow","home","honey","hood","hope","horn","horror","horse",
  "hospital","host","hotel","hour","hover","hub","huge","human",
  "humble","humor","hundred","hungry","hunt","hurdle","hurry","hurt",
  "hybrid","ice","icon","idea","identify","idle","ignore","image",
  "immune","impact","impose","improve","impulse","inch","include","income",
  "increase","index","indicate","indoor","industry","infant","inflict","inform",
  "initial","inner","innocent","input","inquiry","insane","insect","inside",
  "inspire","install","intact","interest","into","invest","invite","iron",
  "island","isolate","issue","item","ivory","jacket","jaguar","jazz",
  "jealous","jeans","jelly","jewel","job","join","joke","journey",
  "joy","judge","juice","jump","jungle","junior","junk","just",
  "kangaroo","keen","keep","kettle","key","kick","kid","kidney",
  "kind","kingdom","kiss","kit","kitchen","kite","kitten","kiwi",
  "knee","knife","knock","know","label","labor","ladder","lady",
  "lake","lamp","language","laptop","large","later","latin","laugh",
  "laundry","lava","law","lawn","lawsuit","layer","lazy","leader",
  "leaf","learn","leave","lecture","left","legal","legend","leisure",
  "lemon","length","lens","leopard","lesson","letter","level","liberty",
  "library","license","life","lift","light","like","limb","limit",
  "link","lion","liquid","list","little","live","lizard","load",
  "loan","lobster","local","lock","logic","lonely","long","loop",
  "lottery","loud","lounge","love","loyal","lucky","lumber","lunar",
  "lunch","luxury","lyrics","machine","mad","magic","magnet","maid",
  "mail","main","major","make","mammal","manage","mandate","mango",
];

/**
 * Generate a random passphrase using cryptographic randomness.
 * @param wordCount Number of words (default 6, ~60 bits of entropy)
 * @returns Hyphen-separated passphrase, e.g. "correct-horse-battery-staple-anchor-brave"
 */
export function generatePassphrase(wordCount = 6): string {
  const indices = new Uint32Array(wordCount);
  crypto.getRandomValues(indices);
  const words: string[] = [];
  for (let i = 0; i < wordCount; i++) {
    words.push(WORDS[indices[i] % WORDS.length]);
  }
  return words.join("-").toUpperCase();
}
